tracks:
  academic:
    stem:
      subjects:
        - Math
        - Science
      ncae:
        - Scientific Ability
        - Mathematical Ability
        - Logical Reasoning Ability
        - Visual Manipulative Skill
        - STEM
    gas:
      subjects:
        - English
        - Filipino
        - Social Studies
        - Math
        - Science
        - Values Education
        - MAPEH
        - Computer
        - TLE
      ncae:
        - Scientific Ability
        - Mathematical Ability
        - Reading Comprehension
        - Verbal Ability
        - Clerical Ability
        - Logical Reasoning Ability
        - Visual Manipulative Skill
    abm:
      subjects:
        - Math
        - English
      ncae:
        - Mathematical Ability
        - Reading Comprehension
        - Verbal Ability
        - ABM
    humss:
      subjects:
        - English
        - Values Education
        - Computer
      ncae:
        - Reading Comprehension
        - Verbal Ability
        - Non Verbal Ability
multiplier:
  grades: 1
  ncae: 1
  awards: 1